export enum Tipo {
    ENTREGADOMICILIOMARKETPLACE = "MARKETPLACE",
    ENTREGADOMICILIOROPA = "ROPA",
    ENTREGATIENDAROPA = "ROPA",
    ENTREGADOMICILIOMUEBLES = "MUEBLES",
    ENTREGATIENDAMUEBLES = "MUEBLES"
}